-- Tabla de configuraciones unificada para MedForge
CREATE TABLE IF NOT EXISTS app_settings (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    category VARCHAR(100) DEFAULT NULL,
    name VARCHAR(191) NOT NULL,
    value LONGTEXT DEFAULT NULL,
    type VARCHAR(50) DEFAULT 'text',
    autoload TINYINT(1) NOT NULL DEFAULT 0,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_app_settings_name (name),
    KEY idx_app_settings_category (category),
    KEY idx_app_settings_autoload (autoload)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO app_settings (category, name, value, type, autoload) VALUES
    ('general', 'companyname', '', 'text', 1),
    ('general', 'company_legal_name', '', 'text', 0),
    ('general', 'companyaddress', '', 'text', 0),
    ('general', 'company_city', '', 'text', 0),
    ('general', 'company_country', '', 'text', 0),
    ('general', 'company_vat', '', 'text', 0),
    ('general', 'companyphone', '', 'text', 0),
    ('general', 'companyemail', '', 'email', 1),
    ('general', 'companywebsite', '', 'text', 0),
    ('branding', 'company_logo', '', 'text', 0),
    ('branding', 'company_logo_dark', '', 'text', 0),
    ('branding', 'company_logo_small', '', 'text', 0),
    ('branding', 'companysignature', '', 'text', 0),
    ('branding', 'pdf_text_color', '#2D2D2D', 'color', 0),
    ('branding', 'pdf_table_heading_color', '#145388', 'color', 0),
    ('branding', 'admin_default_theme', 'default', 'text', 0),
    ('email', 'mail_engine', 'phpmailer', 'text', 1),
    ('email', 'smtp_host', '', 'text', 0),
    ('email', 'smtp_port', '465', 'number', 0),
    ('email', 'smtp_encryption', '', 'text', 0),
    ('email', 'smtp_email', '', 'email', 0),
    ('email', 'smtp_username', '', 'text', 0),
    ('email', 'smtp_password', '', 'password', 0),
    ('email', 'email_header', '', 'textarea', 0),
    ('email', 'email_footer', '', 'textarea', 0),
    ('email', 'email_signature', '', 'textarea', 0),
    ('email', 'email_from_name', '', 'text', 0),
    ('email', 'email_from_address', '', 'email', 0),
    ('localization', 'default_language', 'spanish', 'text', 1),
    ('localization', 'timezone', 'America/Guayaquil', 'text', 1),
    ('localization', 'dateformat', 'd/m/Y', 'text', 1),
    ('localization', 'time_format', 'H:i', 'text', 1),
    ('localization', 'default_currency', 'USD', 'text', 0),
    ('notifications', 'notifications_email_enabled', '1', 'checkbox', 0),
    ('notifications', 'notifications_sms_enabled', '0', 'checkbox', 0),
    ('notifications', 'notifications_daily_summary', '0', 'checkbox', 0)
ON DUPLICATE KEY UPDATE
    category = VALUES(category),
    type = VALUES(type),
    autoload = VALUES(autoload);
